# -*- coding: utf-8 -*-
"""main assignmet1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yFlZZN4lhq_xRcIKeegpaVZy34er9RY7
"""

el=["abc@gmail.com"]
p=["abc"]
dic={"abc@gmail.com":"abc"}
def dashbord():
 
  print("Enter 1 to Register or enter 2 to loggin")
  choice= int(input())
  if choice==1:
    register()
  elif choice==2:
    loggin()
  else:
    print("invalid entry, please enter your choice again")
    dashbord()

# register function starts

def register():
  
  import re
  print("To Register please input email id and password")
  print("NOTE: password should contain atleast one lowercase, one uppercase, one digit and one special character")
  email=input("Email id: ")
  
#email pattern checking

  email_check=re.compile("\A[a-zA-z]+[a-zA-Z0-9\_]+@+[a-zA-z]+\.+[a-zA-z]+")
  email_ans=email_check.findall(email)

  if(email_ans):
    pass
      # email is valid
  else:
    print("inavlid email!/email id alredy exsist, please enter valid email")
    print(email_ans)
    register()

# email availablity checking
  if email in el:
    print("duplicate")
    register()
  else:
    el.append(email)

#password pattern checking

  password=input("Password: ")
  Pattern= re.compile("^.*(?=.{5,})(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[@#$%^&+=]).*$")
  password_ans=Pattern.findall(password)

  if (password_ans):
    p.append(password)
    dic[email]=password
    print("dic:")
    print(dic)
    print("Registration success!!")
    
    # instert data in file and creating a list to store email and password

    file= open("/content/database1.txt", "a") 
    file.write(email+","+ password+"/n")
    file.close()
    #file= open("/database1.txt", "r") 

    #for i in file:
      #l = i.split(",")
      # a=a.strip()
      # b = b.strip()
      # el.append(a)
      # p.append(b)
      #data= dict(zip(el,p))

      #print(data)
  
  else:
    print("invalid password")
  
    register()

  
# loggin function starts  

def loggin():
  print("enter registerd email id and password")
  email=input("Email id: ")

  if email in el:
    print( "hi!!" )

    password= input("password: ")
    if password in p:
      print("loggin success!! welcome back mr smarty pants")
    else:
      print("invalid password")

      print("enter L to loggin or F to Retrive the password")
    
      fpassword=input("input your choice L or F: ").strip()
      if fpassword== ("L" or "l"):
        loggin()
      elif fpassword==("F" or "f"):
        print("Your password is :")
        print(dic[email])
        

  else:
    print("please enter registed email to login or input 1 to register")
    dashbord()

# forgot password
  
dashbord()

from google.colab import drive
drive.mount('/content/drive')